### ISSUE TITLE
App Release Checklist

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr-up#80]
This is a list of all the things that we need to complete in order for us to release the app publicly on the 15th March 2014.
### App Dev and Testing
- [x] Catchup on Monday 10th March with @stellanl, @Anna-Marthe and @adriancollier for status review
- [x] Complete the final major issue #75 
- [x] Code-Review done by @ichinaski 
- [x] Release final Beta Version to Internal Akvo audience
- [x] Get sign off on new improvements from @adriancollier
- [x] Get sign off on new improvements from @stellanl 
- [ ] Get sign off on new improvements from @loicsans 
- [ ] Get sign off on new improvements from @bjelkeman 
- [x] Get sign off on new improvements from @Anna-Marthe 
- [ ] Get sign off on new improvements from @rumca 
- [x] Add Beta Test closed update to RSR Project
### Google Play Store
- [x] Load the App into the Google Play Store
- [x] Get App signed off by Google for public consumption
### Communication Info
- [x] Prepare Blog piece for launch of app
- [x] Prepare website page with information about App on akvo-web
- [ ] Prepare Tender info on How to get App from Google Play and F-Droid Stores
- [x] Prepare Tender info on How to use App
